export interface PlantUpsertDto {
  id?: number,
  name: string,
  scientificName: string,
  imageUrl?: string,
  image?: File,
  family: string,
  growthId: number,
  foliageId: number,
  shapeId: number,
  waterId: number,
  lifespanId: number,
  difficultyId: number,
  typeId: number,
  // bloomSeasonIds?: number[],
  // harvestSeasonIds?: number[],
  // pruneSeasonIds?: number[],
  // plantingSeasonIds?: number[],
  // usageIds?: number[],
  // lightIds?: number[],
  // plantingMethodIds?: number[],
  // soilHumiditieIds?: number[],
  // soilPhIds?: number[],
  // soilTypeIds?: number[],
  // lowHeight?: number | null,
  // highHeight?: number | null,
  // lowWidth?: number | null,
  // highWidth?: number | null,
  // contentUrl?: String | null,
  // content?: String
}